### PR TITLE
Fix breakpoint click events

### LINKED ISSUE #2848: Impossible to unset breakpoints on all browsers
You can't see the cursor, but I'm clicking all around the breakpoint and have not been able to unset one.

### PR DESCRIPTION
**Pull request by riknoll**
Fixes https://github.com/microsoft/pxt-microbit/issues/2848

The super class `isVisible` just checks to see if `this.bubble_` is defined, but breakpoints don't have bubbles.

### CODE REVIEW

**Review by shakao — APPROVED** [review]

File: core/pxt_breakpoint.js [hunk 1]
```diff
@@ -135,7 +135,7 @@ Blockly.Breakpoint.prototype.setVisible = function(visible) {
  * @return {boolean} True if the breakpoint is Set.
  */
 Blockly.Breakpoint.prototype.isVisible = function() {
-  return !!this.set_ && Blockly.Breakpoint.superClass_.isVisible.call(this);
+  return !!this.set_
```
Comment (shakao) [inline core/pxt_breakpoint.js]:
```suggestion
  return !!this.set_;
```

Comment (shakao) [reply core/pxt_breakpoint.js]: nitpick

Comment (riknoll) [reply core/pxt_breakpoint.js]: I knew you'd catch that. I was just too lazy to add a commit!
