### PR TITLE
Additional fixes for insertion flickering, number validation, CSS

### LINKED ISSUE #5932: Dropdowns are not disabled in readonly mode (blockly)
The css query needs to account for .blocklyNonEditableText as well.

https://github.com/microsoft/pxt-blockly/blob/6dc75f02c7b1891b1f4d9a81615934b2aa76b2d5/core/css.js#L458

### PR DESCRIPTION
**Pull request by shakao**
Fixes for:
- Block flickering while dragging to insert/highlight
- Decimal validation
- CSS for disabled dropdown (fixes https://github.com/microsoft/pxt/issues/5932) and context menu

### CODE REVIEW

File: core/field_number.js [hunk 1]
```diff
@@ -142,24 +142,37 @@ Blockly.FieldNumber.prototype.getNumRestrictor = function(opt_min, opt_max,
...
+      precisionString.length - (decimalIndex + 1);
+  this.decimalAllowed_ = (typeof this.precision_ == 'undefined') ||
+      isNaN(this.precision_) || (this.precision_ == 0) ||
+      (Math.floor(this.precision_) != this.precision_);
+
+  min = parseFloat(min);
   this.min_ = isNaN(min) ? -Infinity : min;
-  let max = parseFloat(opt_max);
+  this.negativeAllowed_ = (typeof this.min_ == 'undefined') || isNaN(this.min_) ||
+  this.min_ < 0;
```
Comment (jwunderl) [inline core/field_number.js]:
```suggestion
      this.min_ < 0;
```
nit: spacing here

**Review by jwunderl — APPROVED** [review]

File: core/css.js [hunk 2]
```diff
@@ -1067,8 +1069,6 @@ Blockly.Css.CONTENT = [
     'outline: none;',
     'padding: 4px 0;',
     'position: absolute;',
-    'overflow-y: auto;',
```
Comment (samelhusseini) [inline core/css.js:1070]: Hey @shakao, just wondering why this was removed?

Comment (shakao) [reply core/css.js:1070]: it was causing an unnecessary scrollbar to appear in our context menu--i think actually the better fix would be to put this back and add content-box sizing to the .goog-menu; i'll do that in the next batch of updates
