### PR TITLE
Show modal for text input with touch

### LINKED ISSUE #3496: On Screen Keyboard issues
This bug was reported by the Irish Microsoft DreamSpace Team.
They are using the Surface Hub 2 with new Edge and when clicking into a text field, the on-screen keyboard is not popping up.

I was able to reproduce a similar issue on my Surface Pro where the on-screen keyboard flashes momentarily and then disappears.

### PR DESCRIPTION
**Pull request by livcheerful**
fixes https://github.com/microsoft/pxt-microbit/issues/3496

The issue was we were first focusing on the workspace, then the text input, and then the workspace again, but instead of looking more into that, I saw that we were using a prompt editor for mobile browsers because of focus and on screen keyboard issues, so I thought making general touch events trigger it would be a good fix. If you guys think it's better to keep it inline then I can do it the other way :D 

(this is what it looks like on my Surface)
image

### CODE REVIEW

File: core/field_textinput.js [hunk 1]
```diff
@@ -386,9 +386,15 @@ Blockly.FieldTextInput.prototype.showEditor_ = function(_opt_e,
...
   var readOnly = opt_readOnly || false;
+  var isTouchEvent = undefined;
+  if (_opt_e instanceof PointerEvent) {
+    isTouchEvent = _opt_e.pointerType === "touch";
+  }
+
   if (!quietInput && (Blockly.utils.userAgent.MOBILE ||
                       Blockly.utils.userAgent.ANDROID ||
-                      Blockly.utils.userAgent.IPAD)) {
+                      Blockly.utils.userAgent.IPAD) ||
```
Comment (jwunderl) [inline core/field_textinput.js]: I think the `|| isTouchEvent` should be with the other ios events inside the paranetheses, so quietInput has an effect?

**Review by jwunderl — APPROVED** [review]

File: core/field_textinput.js (hunk 1 above)
Comment (livcheerful) [reply core/field_textinput.js]: oh shoot yes something got messed up ty joey

**Comment by shakao** [comment]
blockly has a builtin "isTouchEvent" function: https://github.com/microsoft/pxt-blockly/blob/develop/core/touch.js#L236 but does this preserve the current drag behavior? right now i can drag a block even if the first place i "touched" is a text input, would this pop up the keyboard instead?

**Comment by livcheerful** [comment]
> blockly has a builtin "isTouchEvent" function: https://github.com/microsoft/pxt-blockly/blob/develop/core/touch.js#L236 but does this preserve the current drag behavior? right now i can drag a block even if the first place i "touched" is a text input, would this pop up the keyboard instead?

This is excellent :O And I just tested it with microbit -- drag events still work even if I'm dragging by the text field XD it's only very precise, no planar movement that will trigger this.

**Review by shakao — APPROVED** [review]
